import SessionWraper from "./component/SessionWraper";
import "./globals.css";
export const metadata = {
  title: "superhero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWraper>
        <body>
          {children}
        </body>
      </SessionWraper>
    </html>
  );
}
